name: C++ Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt update && sudo apt install -y g++

    - name: Compile main.cpp
      run: |
        g++ -o food-system ./src/main.cpp
        echo "✅ Build completed"
